modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license="${mod_license}"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
Credits = "Thanks to Dev for teaching me how to do this, and thanks to KaupenJoe for his Java and modding tutorials for Minecraft!"
description = '''${mod_description}'''